# Generated by Django 3.2.21 on 2023-09-06 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0003_pokemonentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='appeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 11, 35, 13, 178492, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='disappeared_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 6, 11, 35, 17, 588813, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
