# Generated by Django 3.2.21 on 2023-09-07 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_auto_20230907_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='next_evo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution', to='pokemon_entities.pokemon'),
        ),
    ]
