# Generated by Django 3.2.21 on 2023-09-07 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0008_pokemon_next_evo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='next_evo',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_evo', to='pokemon_entities.pokemon', verbose_name='прошлая эволюция'),
        ),
    ]
